### ISSUE TITLE
Minor - missing spelling dir in template, config file updates...

### ISSUE THREAD

**Issue by seghcder** [keiffster/template-y#1]
I used this as the template for v1 upgrade and removed all the duplicates from ybot. So far so good.

A few minor issues:

- Missing spelling directory placeholder? 
- Perhaps move the bot section in config.yaml to the top so its easier to compare back to the others in y-bot.
- I used $BOT_ROOT instead of ./ to refer to the "template" bot.
- The ../program-y/... is relative to the starting directory when running python, not $BOT_ROOT. Perhaps reference in readme.txt if not using a "standard" structure.
- Perhaps mention (if not already) that in the case of duplicate AIML statements, its the first statement that sticks. You may want to move the "template" AIML dir above the y-bot one if you want to "override" y-bot. I haven't got to test the same behavior for sets, maps etc...

**Comment by keiffster** [comment]
I’ll review over next few days and see what I can add or enhance

**Comment by keiffster** [comment]
I've intentionally left spelling out for now, and let users stick with the inbuilt one. Still have concerns about it, so until I have dealt with them, keeps its off the radar for all but power users

bot has now moved, I started doing that in a couple of other projects, just needed a reminder to push it through to template-y

All references to ./ have been replaced with $BOT_ROOT

Updated the root level README.txt to remind people of the relative path requirements

In terms of AIML, I am going to add something to the wiki about overrides, but a word of caution not to use it. You should try and stick with clear delineation of grammars from those provided by program-y and your own. Changes in either could have major impacts on the other
